project_id = "ljgbjiixeoxxqpejnmjx"

[functions.schoolpay-webhook]
verify_jwt = false

[functions.schoolpay-sync]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.seed-sample-accounts]
verify_jwt = false

[functions.send-signup-otp]
verify_jwt = false

[functions.verify-signup-otp]
verify_jwt = false