import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/hooks/use-database";
import { useTenant } from "@/hooks/use-tenant";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";
import { Plus, FileText, Calendar, Edit, Eye, XCircle, AlertTriangle } from "lucide-react";
import { format, differenceInDays } from "date-fns";
import { Checkbox } from "@/components/ui/checkbox";

export default function RentalLeases() {
  const { data: tenantData } = useTenant();
  const tenantId = tenantData?.tenantId;
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [lossDialogOpen, setLossDialogOpen] = useState(false);
  const [selectedLeaseForLoss, setSelectedLeaseForLoss] = useState<any>(null);
  const [lossData, setLossData] = useState({
    outstanding_balance: '',
    termination_reason: '',
  });
  const [editingLease, setEditingLease] = useState<any>(null);
  const [formData, setFormData] = useState({
    unit_id: '',
    rental_tenant_id: '',
    start_date: format(new Date(), 'yyyy-MM-dd'),
    end_date: '',
    monthly_rent: '',
    deposit_amount: '',
    deposit_paid: '',
    deposit_months: 2, // Default to 2 months upfront in Uganda
    payment_due_day: 1,
    late_fee_amount: '',
    late_fee_grace_days: 5,
    billing_period: 'monthly',
    status: 'active',
    terms_and_conditions: '',
    special_conditions: '',
  });

  const { data: units = [] } = useQuery({
    queryKey: ['rental-units-available', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rental_units')
        .select('*, rental_properties(name)')
        .eq('tenant_id', tenantId!)
        .eq('is_active', true);
      if (error) throw error;
      return data;
    }
  });

  const { data: rentalTenants = [] } = useQuery({
    queryKey: ['rental-tenants-active', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rental_tenants')
        .select('*')
        .eq('tenant_id', tenantId!)
        .eq('status', 'active');
      if (error) throw error;
      return data;
    }
  });

  const { data: leases = [], isLoading } = useQuery({
    queryKey: ['leases', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('leases')
        .select('*, rental_units(unit_number, rental_properties(name)), rental_tenants(full_name)')
        .eq('tenant_id', tenantId!)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data;
    }
  });

  const createMutation = useMutation({
    mutationFn: async (data: typeof formData) => {
      const { error } = await supabase.from('leases').insert({
        ...data,
        tenant_id: tenantId,
        lease_number: '', // Will be auto-generated by trigger
        monthly_rent: parseFloat(data.monthly_rent) || 0,
        deposit_amount: parseFloat(data.deposit_amount) || 0,
        deposit_paid: parseFloat(data.deposit_paid) || 0,
        deposit_months: data.deposit_months,
        late_fee_amount: parseFloat(data.late_fee_amount) || 0,
        billing_period: data.billing_period,
      });
      if (error) throw error;
      
      // Update unit status to occupied
      await supabase.from('rental_units')
        .update({ status: 'occupied' })
        .eq('id', data.unit_id);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leases'] });
      queryClient.invalidateQueries({ queryKey: ['rental-units'] });
      setOpen(false);
      resetForm();
      toast({ title: "Lease created successfully" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  });

  const updateMutation = useMutation({
    mutationFn: async (data: typeof formData & { id: string }) => {
      const { id, ...updateData } = data;
      const { error } = await supabase.from('leases')
        .update({
          ...updateData,
          monthly_rent: parseFloat(updateData.monthly_rent) || 0,
          deposit_amount: parseFloat(updateData.deposit_amount) || 0,
          deposit_paid: parseFloat(updateData.deposit_paid) || 0,
          deposit_months: updateData.deposit_months,
          late_fee_amount: parseFloat(updateData.late_fee_amount) || 0,
          billing_period: updateData.billing_period,
        })
        .eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leases'] });
      setOpen(false);
      setEditingLease(null);
      resetForm();
      toast({ title: "Lease updated successfully" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  });

  // Mark lease as loss mutation
  const markAsLossMutation = useMutation({
    mutationFn: async (data: { leaseId: string, outstanding_balance: number, termination_reason: string }) => {
      const { error } = await supabase.from('leases')
        .update({
          status: 'terminated',
          marked_as_loss: true,
          outstanding_balance: data.outstanding_balance,
          termination_reason: data.termination_reason,
          loss_marked_at: new Date().toISOString(),
        })
        .eq('id', data.leaseId);
      if (error) throw error;
      
      // Get the lease to update the unit status
      const lease = leases.find(l => l.id === data.leaseId);
      if (lease) {
        await supabase.from('rental_units')
          .update({ status: 'available' })
          .eq('id', lease.unit_id);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['leases'] });
      queryClient.invalidateQueries({ queryKey: ['rental-units'] });
      queryClient.invalidateQueries({ queryKey: ['rental-losses'] });
      setLossDialogOpen(false);
      setSelectedLeaseForLoss(null);
      setLossData({ outstanding_balance: '', termination_reason: '' });
      toast({ title: "Lease marked as loss" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  });

  const resetForm = () => {
    setFormData({
      unit_id: '',
      rental_tenant_id: '',
      start_date: format(new Date(), 'yyyy-MM-dd'),
      end_date: '',
      monthly_rent: '',
      deposit_amount: '',
      deposit_paid: '',
      deposit_months: 2,
      payment_due_day: 1,
      late_fee_amount: '',
      late_fee_grace_days: 5,
      billing_period: 'monthly',
      status: 'active',
      terms_and_conditions: '',
      special_conditions: '',
    });
  };

  const handleMarkAsLoss = (lease: any) => {
    setSelectedLeaseForLoss(lease);
    setLossData({
      outstanding_balance: '',
      termination_reason: 'Left without paying',
    });
    setLossDialogOpen(true);
  };

  const handleSubmitLoss = () => {
    if (!selectedLeaseForLoss) return;
    markAsLossMutation.mutate({
      leaseId: selectedLeaseForLoss.id,
      outstanding_balance: parseFloat(lossData.outstanding_balance) || 0,
      termination_reason: lossData.termination_reason,
    });
  };

  const handleEdit = (lease: any) => {
    setEditingLease(lease);
    setFormData({
      unit_id: lease.unit_id,
      rental_tenant_id: lease.rental_tenant_id,
      start_date: lease.start_date,
      end_date: lease.end_date,
      monthly_rent: lease.monthly_rent?.toString() || '',
      deposit_amount: lease.deposit_amount?.toString() || '',
      deposit_paid: lease.deposit_paid?.toString() || '',
      deposit_months: lease.deposit_months || 2,
      payment_due_day: lease.payment_due_day || 1,
      late_fee_amount: lease.late_fee_amount?.toString() || '',
      late_fee_grace_days: lease.late_fee_grace_days || 5,
      billing_period: lease.billing_period || 'monthly',
      status: lease.status,
      terms_and_conditions: lease.terms_and_conditions || '',
      special_conditions: lease.special_conditions || '',
    });
    setOpen(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (editingLease) {
      updateMutation.mutate({ ...formData, id: editingLease.id });
    } else {
      createMutation.mutate(formData);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'active':
        return <Badge className="bg-emerald-500">Active</Badge>;
      case 'expired':
        return <Badge variant="secondary">Expired</Badge>;
      case 'terminated':
        return <Badge variant="destructive">Terminated</Badge>;
      case 'draft':
        return <Badge variant="outline">Draft</Badge>;
      case 'renewed':
        return <Badge className="bg-blue-500">Renewed</Badge>;
      default:
        return <Badge variant="secondary">{status}</Badge>;
    }
  };

  const getDaysRemaining = (endDate: string) => {
    const days = differenceInDays(new Date(endDate), new Date());
    if (days < 0) return <span className="text-destructive">Expired</span>;
    if (days <= 30) return <span className="text-orange-500">{days} days left</span>;
    return <span className="text-muted-foreground">{days} days left</span>;
  };

  // Get units that can be assigned to a lease (available or the current lease's unit when editing)
  // Also show occupied units without an active lease (for correction purposes)
  const availableUnits = units.filter(u => 
    u.status === 'available' || 
    u.status === 'reserved' ||
    editingLease?.unit_id === u.id
  );

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Leases</h1>
          <p className="text-muted-foreground">Manage lease agreements</p>
        </div>
        <Dialog open={open} onOpenChange={(o) => { setOpen(o); if (!o) { setEditingLease(null); resetForm(); } }}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              New Lease
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>{editingLease ? 'Edit Lease' : 'Create New Lease'}</DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label>Unit</Label>
                  <Select 
                    value={formData.unit_id} 
                    onValueChange={v => {
                      const unit = units.find(u => u.id === v);
                      setFormData({ 
                        ...formData, 
                        unit_id: v,
                        monthly_rent: unit?.monthly_rent?.toString() || formData.monthly_rent,
                        deposit_amount: unit?.deposit_amount?.toString() || formData.deposit_amount,
                      });
                    }}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select unit" />
                    </SelectTrigger>
                    <SelectContent>
                      {availableUnits.map(u => (
                        <SelectItem key={u.id} value={u.id}>
                          {(u.rental_properties as any)?.name} - {u.unit_number}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Tenant</Label>
                  <Select value={formData.rental_tenant_id} onValueChange={v => setFormData({ ...formData, rental_tenant_id: v })}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select tenant" />
                    </SelectTrigger>
                    <SelectContent>
                      {rentalTenants.map(t => (
                        <SelectItem key={t.id} value={t.id}>{t.full_name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Start Date</Label>
                  <Input
                    type="date"
                    value={formData.start_date}
                    onChange={e => setFormData({ ...formData, start_date: e.target.value })}
                    required
                  />
                </div>
                <div>
                  <Label>End Date</Label>
                  <Input
                    type="date"
                    value={formData.end_date}
                    onChange={e => setFormData({ ...formData, end_date: e.target.value })}
                    required
                  />
                </div>
                <div>
                  <Label>Monthly Rent (UGX)</Label>
                  <Input
                    type="number"
                    value={formData.monthly_rent}
                    onChange={e => setFormData({ ...formData, monthly_rent: e.target.value })}
                    required
                  />
                </div>
                <div>
                  <Label>Payment Due Day</Label>
                  <Select 
                    value={formData.payment_due_day.toString()} 
                    onValueChange={v => setFormData({ ...formData, payment_due_day: parseInt(v) })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {[1, 5, 10, 15, 20, 25, 28].map(d => (
                        <SelectItem key={d} value={d.toString()}>Day {d}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Upfront Deposit (Months)</Label>
                  <Select 
                    value={formData.deposit_months.toString()} 
                    onValueChange={v => {
                      const months = parseInt(v);
                      const rent = parseFloat(formData.monthly_rent) || 0;
                      setFormData({ 
                        ...formData, 
                        deposit_months: months,
                        deposit_amount: (rent * months).toString()
                      });
                    }}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="1">1 Month</SelectItem>
                      <SelectItem value="2">2 Months</SelectItem>
                      <SelectItem value="3">3 Months</SelectItem>
                      <SelectItem value="4">4 Months</SelectItem>
                      <SelectItem value="6">6 Months</SelectItem>
                      <SelectItem value="12">12 Months</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Total Deposit Required (UGX)</Label>
                  <Input
                    type="number"
                    value={formData.deposit_amount}
                    onChange={e => setFormData({ ...formData, deposit_amount: e.target.value })}
                  />
                </div>
                <div>
                  <Label>Deposit Paid (UGX)</Label>
                  <Input
                    type="number"
                    value={formData.deposit_paid}
                    onChange={e => setFormData({ ...formData, deposit_paid: e.target.value })}
                    placeholder="Amount received"
                  />
                </div>
                <div>
                  <Label>Billing Period</Label>
                  <Select 
                    value={formData.billing_period} 
                    onValueChange={v => setFormData({ ...formData, billing_period: v })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="monthly">Monthly</SelectItem>
                      <SelectItem value="quarterly">Quarterly (3 months)</SelectItem>
                      <SelectItem value="biannual">Bi-Annual (6 months)</SelectItem>
                      <SelectItem value="annual">Annual (12 months)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label>Late Fee (UGX)</Label>
                  <Input
                    type="number"
                    value={formData.late_fee_amount}
                    onChange={e => setFormData({ ...formData, late_fee_amount: e.target.value })}
                  />
                </div>
                <div>
                  <Label>Grace Days</Label>
                  <Input
                    type="number"
                    min="0"
                    value={formData.late_fee_grace_days}
                    onChange={e => setFormData({ ...formData, late_fee_grace_days: parseInt(e.target.value) || 0 })}
                  />
                </div>
                {editingLease && (
                  <div>
                    <Label>Status</Label>
                    <Select value={formData.status} onValueChange={v => setFormData({ ...formData, status: v })}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="active">Active</SelectItem>
                        <SelectItem value="expired">Expired</SelectItem>
                        <SelectItem value="terminated">Terminated</SelectItem>
                        <SelectItem value="renewed">Renewed</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                )}
                <div className="col-span-2">
                  <Label>Special Conditions</Label>
                  <Textarea
                    value={formData.special_conditions}
                    onChange={e => setFormData({ ...formData, special_conditions: e.target.value })}
                    rows={3}
                    placeholder="Any special terms or conditions..."
                  />
                </div>
              </div>
              <div className="flex justify-end gap-2">
                <Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
                <Button type="submit" disabled={createMutation.isPending || updateMutation.isPending}>
                  {editingLease ? 'Update' : 'Create'} Lease
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Lease #</TableHead>
                <TableHead>Property / Unit</TableHead>
                <TableHead>Tenant</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Monthly Rent</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="w-[100px]">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {leases.map(lease => (
                <TableRow key={lease.id}>
                  <TableCell className="font-mono text-sm">{lease.lease_number}</TableCell>
                  <TableCell>
                    <div>
                      <p className="font-medium">{(lease.rental_units as any)?.rental_properties?.name}</p>
                      <p className="text-sm text-muted-foreground">Unit {(lease.rental_units as any)?.unit_number}</p>
                    </div>
                  </TableCell>
                  <TableCell>{(lease.rental_tenants as any)?.full_name}</TableCell>
                  <TableCell>
                    <div className="text-sm">
                      <p>{format(new Date(lease.start_date), 'MMM d, yyyy')} - {format(new Date(lease.end_date), 'MMM d, yyyy')}</p>
                      <p className="text-xs">{getDaysRemaining(lease.end_date)}</p>
                    </div>
                  </TableCell>
                  <TableCell className="font-medium">
                    UGX {Number(lease.monthly_rent).toLocaleString()}
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1">
                      {getStatusBadge(lease.status)}
                      {lease.marked_as_loss && (
                        <Badge variant="destructive" className="text-xs">
                          Loss
                        </Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      <Button variant="ghost" size="icon" onClick={() => handleEdit(lease)} title="Edit">
                        <Edit className="h-4 w-4" />
                      </Button>
                      {lease.status === 'active' && (
                        <Button 
                          variant="ghost" 
                          size="icon" 
                          onClick={() => handleMarkAsLoss(lease)}
                          title="Mark as Loss"
                          className="text-red-500 hover:text-red-600 hover:bg-red-50"
                        >
                          <XCircle className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {leases.length === 0 && !isLoading && (
                <TableRow>
                  <TableCell colSpan={7} className="text-center py-8 text-muted-foreground">
                    No leases found. Create your first lease agreement.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Mark as Loss Dialog */}
      <Dialog open={lossDialogOpen} onOpenChange={setLossDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-red-600">
              <AlertTriangle className="h-5 w-5" />
              Mark Lease as Loss
            </DialogTitle>
            <DialogDescription>
              This will terminate the lease and record the outstanding balance as a loss. This action marks the tenant as having left without paying.
            </DialogDescription>
          </DialogHeader>
          
          {selectedLeaseForLoss && (
            <div className="space-y-4">
              <div className="p-3 bg-muted rounded-lg">
                <p className="font-medium">{(selectedLeaseForLoss.rental_tenants as any)?.full_name}</p>
                <p className="text-sm text-muted-foreground">
                  Unit {(selectedLeaseForLoss.rental_units as any)?.unit_number} - 
                  UGX {Number(selectedLeaseForLoss.monthly_rent).toLocaleString()}/month
                </p>
              </div>

              <div className="space-y-2">
                <Label>Outstanding Balance (UGX)</Label>
                <Input
                  type="number"
                  value={lossData.outstanding_balance}
                  onChange={e => setLossData({ ...lossData, outstanding_balance: e.target.value })}
                  placeholder="Enter amount owed"
                />
              </div>

              <div className="space-y-2">
                <Label>Reason</Label>
                <Select 
                  value={lossData.termination_reason} 
                  onValueChange={v => setLossData({ ...lossData, termination_reason: v })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Left without paying">Left without paying</SelectItem>
                    <SelectItem value="Absconded">Absconded</SelectItem>
                    <SelectItem value="Evicted with balance">Evicted with balance</SelectItem>
                    <SelectItem value="Dispute - unresolved">Dispute - unresolved</SelectItem>
                    <SelectItem value="Other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="flex justify-end gap-2 pt-4">
                <Button variant="outline" onClick={() => setLossDialogOpen(false)}>
                  Cancel
                </Button>
                <Button 
                  variant="destructive" 
                  onClick={handleSubmitLoss}
                  disabled={markAsLossMutation.isPending}
                >
                  Mark as Loss
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}