import { useState, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useTenant } from "@/hooks/use-tenant";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Plus, CreditCard, Printer, Ban, RotateCcw, Eye, AlertTriangle, Download } from "lucide-react";
import { format } from "date-fns";
import html2canvas from "html2canvas";
import RentalIDCard from "@/components/rental/RentalIDCard";

export default function RentalIDCards() {
  const { data: tenantData } = useTenant();
  const tenantId = tenantData?.tenantId;
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [deactivateOpen, setDeactivateOpen] = useState(false);
  const [selectedCard, setSelectedCard] = useState<any>(null);
  const [selectedUnitId, setSelectedUnitId] = useState('');
  const [deactivationReason, setDeactivationReason] = useState('');
  const [isDownloading, setIsDownloading] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const frontCardRef = useRef<HTMLDivElement>(null);
  const backCardRef = useRef<HTMLDivElement>(null);

  // Fetch tenant info for cards
  const { data: tenantInfo } = useQuery({
    queryKey: ['tenant-info', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('tenants')
        .select('name, address, phone, email, logo_url, business_code')
        .eq('id', tenantId!)
        .single();
      if (error) throw error;
      return data;
    }
  });

  // Fetch units for dropdown
  const { data: units = [] } = useQuery({
    queryKey: ['rental-units-all', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rental_units')
        .select('*, rental_properties(name, property_code)')
        .eq('tenant_id', tenantId!)
        .order('unit_number');
      if (error) throw error;
      return data;
    }
  });

  // Fetch ID cards
  const { data: idCards = [], isLoading } = useQuery({
    queryKey: ['rental-id-cards', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('rental_id_cards')
        .select('*, rental_units(unit_number, rental_properties(name)), rental_tenants(full_name)')
        .eq('tenant_id', tenantId!)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data;
    }
  });

  // Fetch active leases to get current holder
  const { data: leases = [] } = useQuery({
    queryKey: ['leases-for-cards', tenantId],
    enabled: !!tenantId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('leases')
        .select('unit_id, rental_tenant_id, rental_tenants(id, full_name)')
        .eq('tenant_id', tenantId!)
        .eq('status', 'active');
      if (error) throw error;
      return data;
    }
  });

  const createMutation = useMutation({
    mutationFn: async (unitId: string) => {
      const unit = units.find(u => u.id === unitId);
      if (!unit) throw new Error('Unit not found');

      // Check if card already exists for this unit
      const existingCard = idCards.find(c => c.unit_id === unitId && c.status === 'active');
      if (existingCard) {
        throw new Error('An active card already exists for this unit');
      }

      // Find current lease holder
      const lease = leases.find(l => l.unit_id === unitId);

      const { error } = await supabase.from('rental_id_cards').insert({
        tenant_id: tenantId,
        unit_id: unitId,
        card_number: '', // Will be generated by trigger
        current_holder_id: lease?.rental_tenant_id || null,
        status: 'active',
        issued_at: new Date().toISOString(),
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['rental-id-cards'] });
      setOpen(false);
      setSelectedUnitId('');
      toast({ title: "ID Card created successfully" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  });

  const updateStatusMutation = useMutation({
    mutationFn: async ({ id, status, reason }: { id: string; status: string; reason?: string }) => {
      const updateData: any = {
        status,
        updated_at: new Date().toISOString(),
      };
      
      if (status === 'lost' || status === 'inactive') {
        updateData.deactivated_at = new Date().toISOString();
        updateData.deactivation_reason = reason || null;
      } else if (status === 'active') {
        updateData.deactivated_at = null;
        updateData.deactivation_reason = null;
      }

      const { error } = await supabase
        .from('rental_id_cards')
        .update(updateData)
        .eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['rental-id-cards'] });
      setDeactivateOpen(false);
      setSelectedCard(null);
      setDeactivationReason('');
      toast({ title: "Card status updated" });
    },
    onError: (error: any) => {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  });

  const handlePrint = () => {
    if (printRef.current) {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>Rental ID Card</title>
              <style>
                body { margin: 0; padding: 20px; font-family: system-ui, sans-serif; }
                @media print { 
                  body { margin: 0; padding: 0; }
                  @page { size: 85.6mm 54mm; margin: 0; }
                }
              </style>
            </head>
            <body>${printRef.current.innerHTML}</body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
  };

  const handleDownloadPNG = async () => {
    if (!selectedCard) return;
    
    setIsDownloading(true);
    const holderName = (selectedCard.rental_tenants as any)?.full_name || 'Unknown';
    const sanitizedName = holderName.replace(/[^a-zA-Z0-9]/g, '_');
    
    try {
      // CR80 standard card size: 85.6mm x 54mm at 300 DPI = 1011 x 638 pixels
      const downloadCard = async (ref: HTMLDivElement | null, suffix: string): Promise<boolean> => {
        if (!ref) {
          console.error(`No ref found for ${suffix}`);
          return false;
        }
        
        const canvas = await html2canvas(ref, {
          scale: 4, // High resolution for print quality
          backgroundColor: '#ffffff',
          useCORS: true,
          logging: false,
          allowTaint: true,
        });
        
        const link = document.createElement('a');
        link.download = `${sanitizedName}_${suffix}.png`;
        link.href = canvas.toDataURL('image/png');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        return true;
      };
      
      // Download front card
      await downloadCard(frontCardRef.current, 'Front');
      
      // Wait for browser to process first download
      await new Promise(resolve => setTimeout(resolve, 500));
      
      // Download back card
      await downloadCard(backCardRef.current, 'Back');
      
      toast({ title: "ID Card images downloaded" });
    } catch (error) {
      console.error('Error downloading cards:', error);
      toast({ title: "Error downloading cards", variant: "destructive" });
    } finally {
      setIsDownloading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'active':
        return <Badge className="bg-emerald-500">Active</Badge>;
      case 'inactive':
        return <Badge variant="secondary">Inactive</Badge>;
      case 'lost':
        return <Badge variant="destructive">Lost</Badge>;
      case 'returned':
        return <Badge className="bg-blue-500">Returned</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };

  // Filter units without active cards
  const availableUnits = units.filter(u => 
    !idCards.some(c => c.unit_id === u.id && c.status === 'active')
  );

  return (
    <div className="space-y-4 md:space-y-6 p-4 md:p-6 pb-24 md:pb-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">ID Cards</h1>
          <p className="text-muted-foreground">Manage property-owned tenant ID cards</p>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Create Card
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create ID Card</DialogTitle>
              <DialogDescription>Create a new ID card for a unit. The card belongs to the property.</DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              <div>
                <Label>Select Unit</Label>
                <Select value={selectedUnitId} onValueChange={setSelectedUnitId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a unit without an active card" />
                  </SelectTrigger>
                  <SelectContent>
                    {availableUnits.map(u => (
                      <SelectItem key={u.id} value={u.id}>
                        {(u.rental_properties as any)?.name} - {u.unit_number}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
                <Button 
                  onClick={() => createMutation.mutate(selectedUnitId)}
                  disabled={!selectedUnitId || createMutation.isPending}
                >
                  Create Card
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Summary */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Cards</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{idCards.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Active</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-emerald-600">
              {idCards.filter(c => c.status === 'active').length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Lost</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-destructive">
              {idCards.filter(c => c.status === 'lost').length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Returned</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">
              {idCards.filter(c => c.status === 'returned').length}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Cards Table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <CreditCard className="h-5 w-5" />
            ID Cards
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Card Number</TableHead>
                <TableHead>Property / Unit</TableHead>
                <TableHead>Current Holder</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Issued</TableHead>
                <TableHead className="w-[150px]">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {idCards.map(card => (
                <TableRow key={card.id}>
                  <TableCell className="font-mono font-bold">{card.card_number}</TableCell>
                  <TableCell>
                    <div className="font-medium">{(card.rental_units as any)?.rental_properties?.name}</div>
                    <div className="text-sm text-muted-foreground">{(card.rental_units as any)?.unit_number}</div>
                  </TableCell>
                  <TableCell>
                    {(card.rental_tenants as any)?.full_name || (
                      <span className="text-muted-foreground">No holder</span>
                    )}
                  </TableCell>
                  <TableCell>{getStatusBadge(card.status)}</TableCell>
                  <TableCell>
                    {card.issued_at ? format(new Date(card.issued_at), 'MMM d, yyyy') : '-'}
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-1">
                      <Button 
                        variant="ghost" 
                        size="icon"
                        onClick={() => {
                          setSelectedCard(card);
                          setPreviewOpen(true);
                        }}
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button 
                        variant="ghost" 
                        size="icon"
                        onClick={() => {
                          setSelectedCard(card);
                          setPreviewOpen(true);
                          setTimeout(handlePrint, 300);
                        }}
                      >
                        <Printer className="h-4 w-4" />
                      </Button>
                      {card.status === 'active' && (
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={() => {
                            setSelectedCard(card);
                            setDeactivateOpen(true);
                          }}
                        >
                          <Ban className="h-4 w-4 text-destructive" />
                        </Button>
                      )}
                      {(card.status === 'lost' || card.status === 'inactive') && (
                        <Button 
                          variant="ghost" 
                          size="icon"
                          onClick={() => updateStatusMutation.mutate({ id: card.id, status: 'active' })}
                        >
                          <RotateCcw className="h-4 w-4 text-emerald-600" />
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {idCards.length === 0 && !isLoading && (
                <TableRow>
                  <TableCell colSpan={6} className="text-center py-8 text-muted-foreground">
                    No ID cards created yet
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Preview Dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>ID Card Preview</DialogTitle>
          </DialogHeader>
          {selectedCard && tenantInfo && (
            <div className="space-y-4">
              {/* Combined view for print */}
              <div className="hidden">
                <div ref={printRef}>
                  <RentalIDCard
                    cardNumber={selectedCard.card_number}
                    unitNumber={(selectedCard.rental_units as any)?.unit_number}
                    propertyName={(selectedCard.rental_units as any)?.rental_properties?.name}
                    holderName={(selectedCard.rental_tenants as any)?.full_name}
                    propertyCode={tenantInfo.business_code}
                    businessName={tenantInfo.name}
                    businessPhone={tenantInfo.phone}
                    businessAddress={tenantInfo.address}
                    logoUrl={tenantInfo.logo_url}
                    issuedDate={selectedCard.issued_at ? format(new Date(selectedCard.issued_at), 'MMM d, yyyy') : undefined}
                    side="both"
                  />
                </div>
              </div>
              
              {/* Visible preview with separate refs for download */}
              <div className="flex flex-col items-center gap-4">
                <div ref={frontCardRef}>
                  <RentalIDCard
                    cardNumber={selectedCard.card_number}
                    unitNumber={(selectedCard.rental_units as any)?.unit_number}
                    propertyName={(selectedCard.rental_units as any)?.rental_properties?.name}
                    holderName={(selectedCard.rental_tenants as any)?.full_name}
                    propertyCode={tenantInfo.business_code}
                    businessName={tenantInfo.name}
                    businessPhone={tenantInfo.phone}
                    businessAddress={tenantInfo.address}
                    logoUrl={tenantInfo.logo_url}
                    issuedDate={selectedCard.issued_at ? format(new Date(selectedCard.issued_at), 'MMM d, yyyy') : undefined}
                    side="front"
                  />
                </div>
                <div ref={backCardRef}>
                  <RentalIDCard
                    cardNumber={selectedCard.card_number}
                    unitNumber={(selectedCard.rental_units as any)?.unit_number}
                    propertyName={(selectedCard.rental_units as any)?.rental_properties?.name}
                    holderName={(selectedCard.rental_tenants as any)?.full_name}
                    propertyCode={tenantInfo.business_code}
                    businessName={tenantInfo.name}
                    businessPhone={tenantInfo.phone}
                    businessAddress={tenantInfo.address}
                    logoUrl={tenantInfo.logo_url}
                    issuedDate={selectedCard.issued_at ? format(new Date(selectedCard.issued_at), 'MMM d, yyyy') : undefined}
                    side="back"
                  />
                </div>
              </div>
            </div>
          )}
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => setPreviewOpen(false)}>Close</Button>
            <Button variant="secondary" onClick={handleDownloadPNG} disabled={isDownloading}>
              <Download className="h-4 w-4 mr-2" />
              {isDownloading ? "Downloading..." : "Download PNG"}
            </Button>
            <Button onClick={handlePrint}>
              <Printer className="h-4 w-4 mr-2" />
              Print
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Deactivate Dialog */}
      <Dialog open={deactivateOpen} onOpenChange={setDeactivateOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-destructive" />
              Deactivate Card
            </DialogTitle>
            <DialogDescription>
              Mark this card as lost or inactive. This will prevent it from being used for payment proofs.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Reason</Label>
              <Textarea
                value={deactivationReason}
                onChange={e => setDeactivationReason(e.target.value)}
                placeholder="e.g., Card reported lost, tenant moved out without returning..."
                rows={3}
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setDeactivateOpen(false)}>Cancel</Button>
              <Button 
                variant="destructive"
                onClick={() => updateStatusMutation.mutate({ 
                  id: selectedCard?.id, 
                  status: 'lost',
                  reason: deactivationReason 
                })}
              >
                Mark as Lost
              </Button>
              <Button 
                variant="secondary"
                onClick={() => updateStatusMutation.mutate({ 
                  id: selectedCard?.id, 
                  status: 'returned',
                  reason: deactivationReason 
                })}
              >
                Mark as Returned
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
