import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, DropdownMenuSeparator } from "@/components/ui/dropdown-menu";
import { toast } from "@/hooks/use-toast";
import { useTenant } from "@/hooks/use-tenant";
import { Baby, Search, Plus, MoreHorizontal, CheckCircle, Clock, XCircle, Eye, Edit, UserCheck, Filter, Users } from "lucide-react";
import { ECDPupilEnrollmentForm } from "@/components/ecd/ECDPupilEnrollmentForm";
import { LinkParentDialog } from "@/components/ecd/LinkParentDialog";
import { format, differenceInYears } from "date-fns";

const ECD_LEVELS = [
  { value: 'ecd1', label: 'Baby Class', color: 'bg-pink-100 text-pink-800' },
  { value: 'ecd2', label: 'Middle Class', color: 'bg-blue-100 text-blue-800' },
  { value: 'ecd3', label: 'Top Class', color: 'bg-green-100 text-green-800' },
];

export default function ECDPupils() {
  const tenantQuery = useTenant();
  const tenantId = tenantQuery.data?.tenantId;
  const queryClient = useQueryClient();
  
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedLevel, setSelectedLevel] = useState<string>("all");
  const [selectedStatus, setSelectedStatus] = useState<string>("all");
  const [showEnrollmentDialog, setShowEnrollmentDialog] = useState(false);
  const [editingPupil, setEditingPupil] = useState<any>(null);
  const [activeTab, setActiveTab] = useState<string>("enrolled");
  const [linkingPupil, setLinkingPupil] = useState<any>(null);

  // Fetch pupils (ECD students)
  const { data: pupils = [], isLoading } = useQuery({
    queryKey: ['ecd-pupils', tenantId, selectedLevel, selectedStatus],
    enabled: !!tenantId,
    queryFn: async () => {
      let query = supabase
        .from('students')
        .select('*, school_classes(name, section, level)')
        .eq('tenant_id', tenantId)
        .order('created_at', { ascending: false });
      
      // Filter by ECD levels - include students with null ecd_level as they're likely new enrollments
      if (selectedLevel !== 'all') {
        query = query.eq('ecd_level', selectedLevel);
      } else {
        // Show all students with ECD levels OR null (new enrollments)
        query = query.or('ecd_level.in.(ecd1,ecd2,ecd3),ecd_level.is.null');
      }
      
      if (selectedStatus !== 'all') {
        query = query.eq('admission_status', selectedStatus);
      }
      
      const { data, error } = await query;
      if (error) throw error;
      return data;
    },
  });

  // Stats
  const stats = {
    total: pupils.length,
    pending: pupils.filter(p => p.admission_status === 'pending').length,
    approved: pupils.filter(p => p.admission_status === 'approved').length,
    enrolled: pupils.filter(p => p.admission_status === 'enrolled').length,
  };

  // Enroll pupil mutation
  const enrollMutation = useMutation({
    mutationFn: async (data: any) => {
      const pupilData = {
        tenant_id: tenantId!,
        admission_number: '', // Will be auto-generated by trigger
        full_name: data.full_name,
        date_of_birth: data.date_of_birth,
        gender: data.gender,
        photo_url: data.photo_url || null,
        guardian_name: data.guardian_name,
        guardian_phone: data.guardian_phone,
        guardian_email: data.guardian_email || null,
        guardian_address: data.guardian_address,
        guardian_occupation: data.guardian_occupation || null,
        guardian_relationship: data.guardian_relationship,
        emergency_contact_name: data.emergency_contact_name,
        emergency_contact_phone: data.emergency_contact_phone,
        emergency_contact_relationship: data.emergency_contact_relationship || null,
        medical_conditions: data.medical_conditions || null,
        allergies: data.allergies || null,
        previous_school_name: data.previous_school_name || null,
        class_id: data.class_id || null,
        ecd_level: data.ecd_level,
        suggested_class_level: data.suggested_class_level || null,
        nin_optional: data.nin_optional || null,
        admission_notes: data.admission_notes || null,
        admission_status: 'pending',
        payment_status: 'unpaid',
        boarding_status: 'day',
        address: data.guardian_address,
        parent_name: data.guardian_name,
        parent_phone: data.guardian_phone,
        parent_email: data.guardian_email || null,
      };

      if (editingPupil) {
        const { error } = await supabase
          .from('students')
          .update(pupilData)
          .eq('id', editingPupil.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('students')
          .insert([pupilData]);
        if (error) throw error;
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ecd-pupils'] });
      setShowEnrollmentDialog(false);
      setEditingPupil(null);
      toast({
        title: editingPupil ? "Pupil Updated" : "Enrollment Submitted",
        description: editingPupil 
          ? "Pupil information has been updated."
          : "The enrollment application has been submitted for review.",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  // Update status mutation
  const updateStatusMutation = useMutation({
    mutationFn: async ({ pupilId, status }: { pupilId: string; status: string }) => {
      const { error } = await supabase
        .from('students')
        .update({ 
          admission_status: status,
          is_active: status === 'enrolled',
        })
        .eq('id', pupilId);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ecd-pupils'] });
      toast({ title: "Status Updated" });
    },
  });

  const filteredPupils = pupils.filter(pupil =>
    pupil.full_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    pupil.admission_number?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'pending':
        return <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200"><Clock className="h-3 w-3 mr-1" /> Pending</Badge>;
      case 'approved':
        return <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200"><CheckCircle className="h-3 w-3 mr-1" /> Approved</Badge>;
      case 'enrolled':
        return <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200"><UserCheck className="h-3 w-3 mr-1" /> Enrolled</Badge>;
      case 'rejected':
        return <Badge variant="outline" className="bg-red-50 text-red-700 border-red-200"><XCircle className="h-3 w-3 mr-1" /> Rejected</Badge>;
      default:
        return <Badge variant="outline">{status}</Badge>;
    }
  };

  const getLevelBadge = (level: string) => {
    const ecdLevel = ECD_LEVELS.find(l => l.value === level);
    if (!ecdLevel) return null;
    return <Badge className={ecdLevel.color}>{ecdLevel.label}</Badge>;
  };

  const calculateAge = (dob: string) => {
    if (!dob) return '-';
    const years = differenceInYears(new Date(), new Date(dob));
    return `${years} yrs`;
  };

  return (
    <div className="space-y-4 md:space-y-6 p-4 md:p-6 pb-24 md:pb-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <Baby className="h-6 w-6" />
            ECD Pupils
          </h1>
          <p className="text-muted-foreground">
            Manage kindergarten learners and enrollment
          </p>
        </div>
        <Button onClick={() => { setEditingPupil(null); setShowEnrollmentDialog(true); }}>
          <Plus className="h-4 w-4 mr-2" />
          New Enrollment
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="cursor-pointer hover:bg-muted/50" onClick={() => setSelectedStatus('all')}>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Total Pupils</p>
            <p className="text-2xl font-bold">{stats.total}</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:bg-muted/50" onClick={() => setSelectedStatus('pending')}>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Pending Review</p>
            <p className="text-2xl font-bold text-yellow-600">{stats.pending}</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:bg-muted/50" onClick={() => setSelectedStatus('approved')}>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Approved</p>
            <p className="text-2xl font-bold text-blue-600">{stats.approved}</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:bg-muted/50" onClick={() => setSelectedStatus('enrolled')}>
          <CardContent className="p-4">
            <p className="text-sm text-muted-foreground">Enrolled</p>
            <p className="text-2xl font-bold text-green-600">{stats.enrolled}</p>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search by name..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={selectedLevel} onValueChange={setSelectedLevel}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter by class" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Classes</SelectItem>
                {ECD_LEVELS.map(level => (
                  <SelectItem key={level.value} value={level.value}>{level.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={selectedStatus} onValueChange={setSelectedStatus}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Statuses</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="approved">Approved</SelectItem>
                <SelectItem value="enrolled">Enrolled</SelectItem>
                <SelectItem value="rejected">Rejected</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Pupils Table */}
      <Card>
        <CardHeader>
          <CardTitle>Pupils List</CardTitle>
          <CardDescription>
            {filteredPupils.length} pupil{filteredPupils.length !== 1 ? 's' : ''} found
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="text-center py-8 text-muted-foreground">Loading...</div>
          ) : filteredPupils.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Baby className="h-12 w-12 mx-auto mb-2 opacity-50" />
              <p>No pupils found</p>
              <Button 
                variant="outline" 
                className="mt-4"
                onClick={() => { setEditingPupil(null); setShowEnrollmentDialog(true); }}
              >
                <Plus className="h-4 w-4 mr-2" />
                Enroll First Pupil
              </Button>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Pupil</TableHead>
                    <TableHead>Age</TableHead>
                    <TableHead>Class Level</TableHead>
                    <TableHead>Parent/Guardian</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Enrolled</TableHead>
                    <TableHead></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredPupils.map(pupil => (
                    <TableRow key={pupil.id}>
                      <TableCell>
                        <div className="flex items-center gap-3">
                          {pupil.photo_url ? (
                            <img 
                              src={pupil.photo_url} 
                              alt="" 
                              className="w-10 h-10 rounded-full object-cover"
                            />
                          ) : (
                            <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                              <Baby className="h-5 w-5 text-primary" />
                            </div>
                          )}
                          <div>
                            <p className="font-medium">{pupil.full_name}</p>
                            <p className="text-xs text-muted-foreground">{pupil.admission_number}</p>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>{calculateAge(pupil.date_of_birth)}</TableCell>
                      <TableCell>
                        {getLevelBadge(pupil.ecd_level)}
                        {pupil.school_classes?.name && (
                          <p className="text-xs text-muted-foreground mt-1">
                            {pupil.school_classes.name}
                          </p>
                        )}
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="text-sm">{pupil.guardian_name || pupil.parent_name}</p>
                          <p className="text-xs text-muted-foreground">{pupil.guardian_phone || pupil.parent_phone}</p>
                        </div>
                      </TableCell>
                      <TableCell>{getStatusBadge(pupil.admission_status || 'pending')}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {pupil.admission_date ? format(new Date(pupil.admission_date), 'dd MMM yyyy') : '-'}
                      </TableCell>
                      <TableCell>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => { setEditingPupil(pupil); setShowEnrollmentDialog(true); }}>
                              <Edit className="h-4 w-4 mr-2" /> Edit Details
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => setLinkingPupil(pupil)}>
                              <Users className="h-4 w-4 mr-2" /> Link Parents
                            </DropdownMenuItem>
                            <DropdownMenuSeparator />
                            {pupil.admission_status === 'pending' && (
                              <>
                                <DropdownMenuItem onClick={() => updateStatusMutation.mutate({ pupilId: pupil.id, status: 'approved' })}>
                                  <CheckCircle className="h-4 w-4 mr-2" /> Approve
                                </DropdownMenuItem>
                                <DropdownMenuItem 
                                  className="text-red-600"
                                  onClick={() => updateStatusMutation.mutate({ pupilId: pupil.id, status: 'rejected' })}
                                >
                                  <XCircle className="h-4 w-4 mr-2" /> Reject
                                </DropdownMenuItem>
                              </>
                            )}
                            {pupil.admission_status === 'approved' && (
                              <DropdownMenuItem onClick={() => updateStatusMutation.mutate({ pupilId: pupil.id, status: 'enrolled' })}>
                                <UserCheck className="h-4 w-4 mr-2" /> Mark as Enrolled
                              </DropdownMenuItem>
                            )}
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Enrollment Dialog */}
      <Dialog open={showEnrollmentDialog} onOpenChange={setShowEnrollmentDialog}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-hidden">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Baby className="h-5 w-5" />
              {editingPupil ? 'Edit Pupil Details' : 'New Pupil Enrollment'}
            </DialogTitle>
          </DialogHeader>
          <ECDPupilEnrollmentForm
            tenantId={tenantId!}
            initialData={editingPupil ? {
              full_name: editingPupil.full_name,
              date_of_birth: editingPupil.date_of_birth,
              gender: editingPupil.gender,
              photo_url: editingPupil.photo_url || '',
              guardian_name: editingPupil.guardian_name || '',
              guardian_phone: editingPupil.guardian_phone || '',
              guardian_email: editingPupil.guardian_email || '',
              guardian_address: editingPupil.guardian_address || editingPupil.address || '',
              guardian_occupation: editingPupil.guardian_occupation || '',
              guardian_relationship: editingPupil.guardian_relationship || '',
              emergency_contact_name: editingPupil.emergency_contact_name || '',
              emergency_contact_phone: editingPupil.emergency_contact_phone || '',
              emergency_contact_relationship: editingPupil.emergency_contact_relationship || '',
              medical_conditions: editingPupil.medical_conditions || '',
              allergies: editingPupil.allergies || '',
              previous_school_name: editingPupil.previous_school_name || '',
              class_id: editingPupil.class_id || '',
              ecd_level: editingPupil.ecd_level || '',
              suggested_class_level: editingPupil.suggested_class_level || '',
              nin_optional: editingPupil.nin_optional || '',
              admission_notes: editingPupil.admission_notes || '',
              id: editingPupil.id,
            } : undefined}
            onSubmit={(data) => enrollMutation.mutate(data)}
            onCancel={() => { setShowEnrollmentDialog(false); setEditingPupil(null); }}
            isSubmitting={enrollMutation.isPending}
          />
        </DialogContent>
      </Dialog>

      {/* Link Parent Dialog */}
      {linkingPupil && (
        <LinkParentDialog
          open={!!linkingPupil}
          onOpenChange={(open) => !open && setLinkingPupil(null)}
          studentId={linkingPupil.id}
          studentName={linkingPupil.full_name}
          tenantId={tenantId!}
        />
      )}
    </div>
  );
}
