import { useState, useEffect, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { supabase } from "@/integrations/supabase/client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Save, Upload, X, ImageIcon } from "lucide-react";

interface LetterSettingsProps {
  tenantId: string | null;
}

interface SettingsData {
  show_logo: boolean;
  logo_position: string;
  show_school_name: boolean;
  show_address: boolean;
  show_phone: boolean;
  show_email: boolean;
  header_text: string;
  show_signature_line: boolean;
  signature_title: string;
  show_stamp_area: boolean;
  footer_text: string;
  margin_top: number;
  margin_bottom: number;
  margin_left: number;
  margin_right: number;
  line_spacing: number;
  font_family: string;
  font_size: number;
  use_custom_header: boolean;
  custom_header_image_url: string;
  use_custom_footer: boolean;
  custom_footer_image_url: string;
}

const defaultSettings: SettingsData = {
  show_logo: true,
  logo_position: 'center',
  show_school_name: true,
  show_address: true,
  show_phone: true,
  show_email: true,
  header_text: '',
  show_signature_line: true,
  signature_title: 'Head Teacher',
  show_stamp_area: true,
  footer_text: 'This letter was generated by the school management system.',
  margin_top: 20,
  margin_bottom: 20,
  margin_left: 25,
  margin_right: 25,
  line_spacing: 1.5,
  font_family: 'Arial',
  font_size: 12,
  use_custom_header: false,
  custom_header_image_url: '',
  use_custom_footer: false,
  custom_footer_image_url: '',
};

export const LetterSettings = ({ tenantId }: LetterSettingsProps) => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [settings, setSettings] = useState<SettingsData>(defaultSettings);
  const [uploadingHeader, setUploadingHeader] = useState(false);
  const [uploadingFooter, setUploadingFooter] = useState(false);
  const headerInputRef = useRef<HTMLInputElement>(null);
  const footerInputRef = useRef<HTMLInputElement>(null);

  // Fetch existing settings
  const { data: existingSettings, isLoading } = useQuery({
    queryKey: ['letter-settings', tenantId],
    queryFn: async () => {
      if (!tenantId) return null;
      const { data, error } = await supabase
        .from('letter_settings')
        .select('*')
        .eq('tenant_id', tenantId)
        .maybeSingle();
      
      if (error) throw error;
      return data;
    },
    enabled: !!tenantId,
  });

  // Upload image to storage
  const uploadImage = async (file: File, type: 'header' | 'footer'): Promise<string> => {
    const fileExt = file.name.split('.').pop();
    const fileName = `${tenantId}/letterhead-${type}-${Date.now()}.${fileExt}`;
    
    const { error: uploadError, data } = await supabase.storage
      .from('business-logos')
      .upload(fileName, file, { upsert: true });
    
    if (uploadError) throw uploadError;
    
    const { data: urlData } = supabase.storage
      .from('business-logos')
      .getPublicUrl(fileName);
    
    return urlData.publicUrl;
  };

  const handleHeaderUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    setUploadingHeader(true);
    try {
      const url = await uploadImage(file, 'header');
      setSettings({ ...settings, custom_header_image_url: url });
      toast({ title: "Header image uploaded" });
    } catch (error: any) {
      toast({ title: "Upload failed", description: error.message, variant: "destructive" });
    } finally {
      setUploadingHeader(false);
    }
  };

  const handleFooterUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    setUploadingFooter(true);
    try {
      const url = await uploadImage(file, 'footer');
      setSettings({ ...settings, custom_footer_image_url: url });
      toast({ title: "Footer image uploaded" });
    } catch (error: any) {
      toast({ title: "Upload failed", description: error.message, variant: "destructive" });
    } finally {
      setUploadingFooter(false);
    }
  };

  // Update settings when fetched
  useEffect(() => {
    if (existingSettings) {
      setSettings({
        show_logo: existingSettings.show_logo ?? true,
        logo_position: existingSettings.logo_position || 'center',
        show_school_name: existingSettings.show_school_name ?? true,
        show_address: existingSettings.show_address ?? true,
        show_phone: existingSettings.show_phone ?? true,
        show_email: existingSettings.show_email ?? true,
        header_text: existingSettings.header_text || '',
        show_signature_line: existingSettings.show_signature_line ?? true,
        signature_title: existingSettings.signature_title || 'Head Teacher',
        show_stamp_area: existingSettings.show_stamp_area ?? true,
        footer_text: existingSettings.footer_text || '',
        margin_top: existingSettings.margin_top ?? 20,
        margin_bottom: existingSettings.margin_bottom ?? 20,
        margin_left: existingSettings.margin_left ?? 25,
        margin_right: existingSettings.margin_right ?? 25,
        line_spacing: existingSettings.line_spacing ?? 1.5,
        font_family: existingSettings.font_family || 'Arial',
        font_size: existingSettings.font_size ?? 12,
        use_custom_header: existingSettings.use_custom_header ?? false,
        custom_header_image_url: existingSettings.custom_header_image_url || '',
        use_custom_footer: existingSettings.use_custom_footer ?? false,
        custom_footer_image_url: existingSettings.custom_footer_image_url || '',
      });
    }
  }, [existingSettings]);

  // Save settings mutation
  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!tenantId) throw new Error("No tenant ID");

      const { error } = await supabase
        .from('letter_settings')
        .upsert({
          tenant_id: tenantId,
          ...settings,
        }, {
          onConflict: 'tenant_id',
        });
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['letter-settings'] });
      toast({ title: "Settings saved successfully" });
    },
    onError: (error: any) => {
      toast({ title: "Error saving settings", description: error.message, variant: "destructive" });
    },
  });

  if (!tenantId) {
    return <p className="text-muted-foreground">Loading...</p>;
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Letter Layout Settings</CardTitle>
        <CardDescription>Customize how your letters appear when printed</CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin" />
          </div>
        ) : (
          <Tabs defaultValue="header" className="space-y-4">
            <TabsList>
              <TabsTrigger value="header">Header</TabsTrigger>
              <TabsTrigger value="footer">Footer</TabsTrigger>
              <TabsTrigger value="layout">Layout</TabsTrigger>
            </TabsList>

            <TabsContent value="header" className="space-y-4">
              <div className="grid gap-4">
                {/* Custom Header Toggle */}
                <div className="flex items-center justify-between">
                  <div>
                    <Label htmlFor="use_custom_header">Use Custom Letterhead Image</Label>
                    <p className="text-xs text-muted-foreground">Upload your own header design instead of auto-generated</p>
                  </div>
                  <Switch
                    id="use_custom_header"
                    checked={settings.use_custom_header}
                    onCheckedChange={(checked) => setSettings({ ...settings, use_custom_header: checked })}
                  />
                </div>

                {settings.use_custom_header ? (
                  <div className="space-y-3">
                    <Label>Custom Header Image</Label>
                    <input
                      type="file"
                      ref={headerInputRef}
                      accept="image/*"
                      className="hidden"
                      onChange={handleHeaderUpload}
                    />
                    {settings.custom_header_image_url ? (
                      <div className="space-y-2">
                        <div className="relative border rounded-lg overflow-hidden">
                          <img 
                            src={settings.custom_header_image_url} 
                            alt="Custom header" 
                            className="w-full h-32 object-contain bg-muted"
                          />
                          <Button
                            variant="destructive"
                            size="icon"
                            className="absolute top-2 right-2 h-6 w-6"
                            onClick={() => setSettings({ ...settings, custom_header_image_url: '' })}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={() => headerInputRef.current?.click()}
                          disabled={uploadingHeader}
                        >
                          {uploadingHeader ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}
                          Replace Image
                        </Button>
                      </div>
                    ) : (
                      <div 
                        className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:border-primary/50 transition-colors"
                        onClick={() => headerInputRef.current?.click()}
                      >
                        {uploadingHeader ? (
                          <Loader2 className="h-8 w-8 animate-spin mx-auto text-muted-foreground" />
                        ) : (
                          <>
                            <ImageIcon className="h-8 w-8 mx-auto text-muted-foreground" />
                            <p className="mt-2 text-sm text-muted-foreground">Click to upload letterhead image</p>
                            <p className="text-xs text-muted-foreground">Recommended: 800x150px, PNG or JPG</p>
                          </>
                        )}
                      </div>
                    )}
                  </div>
                ) : (
                  <>
                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_logo">Show School Logo</Label>
                      <Switch
                        id="show_logo"
                        checked={settings.show_logo}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_logo: checked })}
                      />
                    </div>

                    {settings.show_logo && (
                      <div className="space-y-2">
                        <Label>Logo Position</Label>
                        <Select
                          value={settings.logo_position}
                          onValueChange={(value) => setSettings({ ...settings, logo_position: value })}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="left">Left</SelectItem>
                            <SelectItem value="center">Center</SelectItem>
                            <SelectItem value="right">Right</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    )}

                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_school_name">Show School Name</Label>
                      <Switch
                        id="show_school_name"
                        checked={settings.show_school_name}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_school_name: checked })}
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_address">Show Address</Label>
                      <Switch
                        id="show_address"
                        checked={settings.show_address}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_address: checked })}
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_phone">Show Phone Number</Label>
                      <Switch
                        id="show_phone"
                        checked={settings.show_phone}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_phone: checked })}
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_email">Show Email</Label>
                      <Switch
                        id="show_email"
                        checked={settings.show_email}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_email: checked })}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="header_text">Header Text / Motto</Label>
                      <Input
                        id="header_text"
                        value={settings.header_text}
                        onChange={(e) => setSettings({ ...settings, header_text: e.target.value })}
                        placeholder="e.g., 'Education for Excellence'"
                      />
                    </div>
                  </>
                )}
              </div>
            </TabsContent>

            <TabsContent value="footer" className="space-y-4">
              <div className="grid gap-4">
                {/* Custom Footer Toggle */}
                <div className="flex items-center justify-between">
                  <div>
                    <Label htmlFor="use_custom_footer">Use Custom Footer Image</Label>
                    <p className="text-xs text-muted-foreground">Upload your own footer design instead of auto-generated</p>
                  </div>
                  <Switch
                    id="use_custom_footer"
                    checked={settings.use_custom_footer}
                    onCheckedChange={(checked) => setSettings({ ...settings, use_custom_footer: checked })}
                  />
                </div>

                {settings.use_custom_footer ? (
                  <div className="space-y-3">
                    <Label>Custom Footer Image</Label>
                    <input
                      type="file"
                      ref={footerInputRef}
                      accept="image/*"
                      className="hidden"
                      onChange={handleFooterUpload}
                    />
                    {settings.custom_footer_image_url ? (
                      <div className="space-y-2">
                        <div className="relative border rounded-lg overflow-hidden">
                          <img 
                            src={settings.custom_footer_image_url} 
                            alt="Custom footer" 
                            className="w-full h-24 object-contain bg-muted"
                          />
                          <Button
                            variant="destructive"
                            size="icon"
                            className="absolute top-2 right-2 h-6 w-6"
                            onClick={() => setSettings({ ...settings, custom_footer_image_url: '' })}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={() => footerInputRef.current?.click()}
                          disabled={uploadingFooter}
                        >
                          {uploadingFooter ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}
                          Replace Image
                        </Button>
                      </div>
                    ) : (
                      <div 
                        className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:border-primary/50 transition-colors"
                        onClick={() => footerInputRef.current?.click()}
                      >
                        {uploadingFooter ? (
                          <Loader2 className="h-8 w-8 animate-spin mx-auto text-muted-foreground" />
                        ) : (
                          <>
                            <ImageIcon className="h-8 w-8 mx-auto text-muted-foreground" />
                            <p className="mt-2 text-sm text-muted-foreground">Click to upload footer image</p>
                            <p className="text-xs text-muted-foreground">Recommended: 800x100px, PNG or JPG</p>
                          </>
                        )}
                      </div>
                    )}
                  </div>
                ) : (
                  <>
                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_signature_line">Show Signature Line</Label>
                      <Switch
                        id="show_signature_line"
                        checked={settings.show_signature_line}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_signature_line: checked })}
                      />
                    </div>

                    {settings.show_signature_line && (
                      <div className="space-y-2">
                        <Label htmlFor="signature_title">Signature Title</Label>
                        <Input
                          id="signature_title"
                          value={settings.signature_title}
                          onChange={(e) => setSettings({ ...settings, signature_title: e.target.value })}
                          placeholder="e.g., Head Teacher"
                        />
                      </div>
                    )}

                    <div className="flex items-center justify-between">
                      <Label htmlFor="show_stamp_area">Show Stamp Area</Label>
                      <Switch
                        id="show_stamp_area"
                        checked={settings.show_stamp_area}
                        onCheckedChange={(checked) => setSettings({ ...settings, show_stamp_area: checked })}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="footer_text">Footer Message</Label>
                      <Textarea
                        id="footer_text"
                        value={settings.footer_text}
                        onChange={(e) => setSettings({ ...settings, footer_text: e.target.value })}
                        placeholder="Message to appear at the bottom of letters"
                        rows={2}
                      />
                    </div>
                  </>
                )}
              </div>
            </TabsContent>

            <TabsContent value="layout" className="space-y-4">
              <div className="grid gap-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="margin_top">Top Margin (mm)</Label>
                    <Input
                      id="margin_top"
                      type="number"
                      min="5"
                      max="50"
                      value={settings.margin_top}
                      onChange={(e) => setSettings({ ...settings, margin_top: parseInt(e.target.value) || 20 })}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="margin_bottom">Bottom Margin (mm)</Label>
                    <Input
                      id="margin_bottom"
                      type="number"
                      min="5"
                      max="50"
                      value={settings.margin_bottom}
                      onChange={(e) => setSettings({ ...settings, margin_bottom: parseInt(e.target.value) || 20 })}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="margin_left">Left Margin (mm)</Label>
                    <Input
                      id="margin_left"
                      type="number"
                      min="5"
                      max="50"
                      value={settings.margin_left}
                      onChange={(e) => setSettings({ ...settings, margin_left: parseInt(e.target.value) || 25 })}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="margin_right">Right Margin (mm)</Label>
                    <Input
                      id="margin_right"
                      type="number"
                      min="5"
                      max="50"
                      value={settings.margin_right}
                      onChange={(e) => setSettings({ ...settings, margin_right: parseInt(e.target.value) || 25 })}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="line_spacing">Line Spacing</Label>
                    <Select
                      value={settings.line_spacing.toString()}
                      onValueChange={(value) => setSettings({ ...settings, line_spacing: parseFloat(value) })}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1">Single (1.0)</SelectItem>
                        <SelectItem value="1.15">Normal (1.15)</SelectItem>
                        <SelectItem value="1.5">1.5 Lines</SelectItem>
                        <SelectItem value="2">Double (2.0)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="font_size">Font Size (pt)</Label>
                    <Input
                      id="font_size"
                      type="number"
                      min="8"
                      max="16"
                      value={settings.font_size}
                      onChange={(e) => setSettings({ ...settings, font_size: parseInt(e.target.value) || 12 })}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label>Font Family</Label>
                  <Select
                    value={settings.font_family}
                    onValueChange={(value) => setSettings({ ...settings, font_family: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Arial">Arial</SelectItem>
                      <SelectItem value="Times New Roman">Times New Roman</SelectItem>
                      <SelectItem value="Georgia">Georgia</SelectItem>
                      <SelectItem value="Verdana">Verdana</SelectItem>
                      <SelectItem value="Calibri">Calibri</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </TabsContent>

            <div className="pt-4">
              <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}>
                {saveMutation.isPending ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Save className="mr-2 h-4 w-4" />
                )}
                Save Settings
              </Button>
            </div>
          </Tabs>
        )}
      </CardContent>
    </Card>
  );
};