-- Create letter_settings table for layout customization
CREATE TABLE public.letter_settings (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  
  -- Header settings
  show_logo BOOLEAN DEFAULT true,
  logo_position TEXT DEFAULT 'center', -- left, center, right
  show_school_name BOOLEAN DEFAULT true,
  show_address BOOLEAN DEFAULT true,
  show_phone BOOLEAN DEFAULT true,
  show_email BOOLEAN DEFAULT true,
  header_text TEXT, -- Custom header text/motto
  
  -- Footer settings
  show_signature_line BOOLEAN DEFAULT true,
  signature_title TEXT DEFAULT 'Head Teacher',
  show_stamp_area BOOLEAN DEFAULT true,
  footer_text TEXT DEFAULT 'This letter was generated by the school management system.',
  
  -- Margins & spacing (in mm)
  margin_top INTEGER DEFAULT 20,
  margin_bottom INTEGER DEFAULT 20,
  margin_left INTEGER DEFAULT 25,
  margin_right INTEGER DEFAULT 25,
  line_spacing NUMERIC DEFAULT 1.5,
  
  -- Font settings
  font_family TEXT DEFAULT 'Arial',
  font_size INTEGER DEFAULT 12,
  
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  
  UNIQUE(tenant_id)
);

-- Create letters table
CREATE TABLE public.letters (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  
  -- Letter details
  title TEXT NOT NULL,
  subject TEXT,
  content TEXT NOT NULL,
  letter_type TEXT NOT NULL DEFAULT 'general', -- general, personalized
  
  -- For personalized letters
  student_id UUID REFERENCES public.students(id) ON DELETE SET NULL,
  class_id UUID REFERENCES public.school_classes(id) ON DELETE SET NULL,
  
  -- Metadata
  letter_date DATE DEFAULT CURRENT_DATE,
  reference_number TEXT,
  
  -- Status
  status TEXT DEFAULT 'draft', -- draft, finalized
  
  created_by UUID,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.letter_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.letters ENABLE ROW LEVEL SECURITY;

-- RLS policies for letter_settings
CREATE POLICY "Users can manage their tenant letter settings"
ON public.letter_settings
FOR ALL
USING (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()))
WITH CHECK (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()));

-- RLS policies for letters
CREATE POLICY "Users can view their tenant letters"
ON public.letters
FOR SELECT
USING (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()));

CREATE POLICY "Users can insert letters for their tenant"
ON public.letters
FOR INSERT
WITH CHECK (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()));

CREATE POLICY "Users can update their tenant letters"
ON public.letters
FOR UPDATE
USING (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()));

CREATE POLICY "Users can delete their tenant letters"
ON public.letters
FOR DELETE
USING (tenant_id IN (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()));

-- Add updated_at triggers
CREATE TRIGGER update_letter_settings_updated_at
BEFORE UPDATE ON public.letter_settings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_letters_updated_at
BEFORE UPDATE ON public.letters
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Add letters module for schools
INSERT INTO business_modules (code, name, description, icon, category, is_core, applicable_business_types, display_order)
VALUES ('letters', 'Letters', 'Create and manage letters for students and parents', 'Mail', 'communication', false, ARRAY['kindergarten', 'primary_school', 'secondary_school'], 85)
ON CONFLICT (code) DO NOTHING;